default: &default
  adapter: postgresql
  encoding: unicode
  reaping_frequency: <%= ENV.fetch('DB_REAP_FREQ') { 5 } %>
  host: 0.0.0.0
  username: postgres
  password: mysecretpassword
  pool: <%= ENV.fetch('DB_POOL_SIZE_WORKER') { 25 } %>

development:
  <<: *default
  database: railstsgen_development

test:
  <<: *default
  database: railstsgen_test


production: &production
  <<: *default
  database: railstsgen_production
  username: railstsgen
  password: <%= ENV['railstsgen_DATABASE_PASSWORD'] %>

beta:
  <<: *production
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
